[build]
  publish = "exampleSite/public"
  command = "hugo -s exampleSite"
  
  [build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
HUGO_VERSION = "0.51"

[context.production.environment]
HUGO_VERSION = "0.51"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
